from typing import Protocol

from app.domain.models.agent_run import (
    AgentRun,
    AgentTask,
    InterruptedRun,
    TaskAttempt,
)


class AgentRunRepository(Protocol):
    async def add(self, run: AgentRun) -> None: ...

    async def get(self, run_id: str) -> AgentRun | None: ...

    async def get_active_by_session(self, session_id: str) -> AgentRun | None: ...

    async def update(self, run: AgentRun) -> None: ...

    async def add_tasks(self, tasks: list[AgentTask]) -> None: ...

    async def list_tasks(self, run_id: str) -> list[AgentTask]: ...

    async def update_task(self, task: AgentTask) -> None: ...

    async def add_attempt(self, attempt: TaskAttempt) -> None: ...

    async def update_attempt(self, attempt: TaskAttempt) -> None: ...

    async def mark_active_interrupted(self, reason: str) -> list[InterruptedRun]: ...

