from typing import Protocol

from app.domain.models.research import (
    EvidenceExcerpt,
    ResearchClaim,
    ResearchSource,
)


class ResearchRepository(Protocol):
    async def add_source(self, source: ResearchSource) -> None: ...

    async def get_source(self, source_id: str) -> ResearchSource | None: ...

    async def list_sources(self, run_id: str) -> list[ResearchSource]: ...

    async def add_evidence(self, evidence: EvidenceExcerpt) -> None: ...

    async def list_evidence(self, run_id: str) -> list[EvidenceExcerpt]: ...

    async def add_claim(self, claim: ResearchClaim) -> None: ...

    async def update_claim(self, claim: ResearchClaim) -> None: ...

    async def list_claims(self, run_id: str) -> list[ResearchClaim]: ...
